package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L);
    builder.put(0x1fb8b5b4786ddf98L, Canvas);
    builder.put(0x1fb8b5b4786ddf8fL, Circle);
    builder.put(0x1fb8b5b4786ddf9cL, Color);
    builder.put(0x45bfd4213db4dcdL, ColorReference);
    builder.put(0x1fb8b5b4786e959eL, Shape);
    builder.put(0x1fb8b5b4786ddf94L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
