package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Canvas", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786ddf98L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/2285776597609734040");
    b.version(3);
    b.aggregate("shapes", 0x1fb8b5b4786ddf9aL).target(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786e959eL).optional(true).ordered(true).multiple(true).origin("2285776597609734042").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Circle", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786ddf8fL);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Shape
    b.super_(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786e959eL);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/2285776597609734031");
    b.version(3);
    b.property("x", 0x1fb8b5b4786ddf90L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734032").done();
    b.property("y", 0x1fb8b5b4786ddf91L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734033").done();
    b.property("radius", 0x1fb8b5b4786ddf92L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734034").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Color", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786ddf9cL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/2285776597609734044");
    b.version(3);
    b.property("colorName", 0x1fb8b5b4786ddf9dL).type(PrimitiveTypeId.STRING).origin("2285776597609734045").done();
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "ColorReference", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x45bfd4213db4dcdL);
    b.class_(false, false, false);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/314123059275189709");
    b.version(3);
    b.associate("target", 0x45bfd4213db4dceL).target(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786ddf9cL).optional(false).origin("314123059275189710").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Shape", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786e959eL);
    b.class_(false, true, false);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/2285776597609780638");
    b.version(3);
    b.aggregate("color", 0x45bfd4213dc1669L).target(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x45bfd4213db4dcdL).optional(false).ordered(true).multiple(false).origin("314123059275241065").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Square", 0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786ddf94L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Shape
    b.super_(0x74ef8b5ff16142dcL, 0x8ce85bdba824f2a9L, 0x1fb8b5b4786e959eL);
    b.origin("r:336307ce-ea22-4af2-b4be-862ecb38b744(NewLanguage.structure)/2285776597609734036");
    b.version(3);
    b.property("x", 0x1fb8b5b4786ddf95L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734037").done();
    b.property("y", 0x1fb8b5b4786ddf96L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734038").done();
    b.property("size", 0x1fb8b5b4786ddf97L).type(PrimitiveTypeId.INTEGER).origin("2285776597609734039").done();
    return b.create();
  }
}
